// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWc2VfQfuRMWAHD7dtaXblAUJtUgyMQJ8',
    appId: '1:572765239328:android:3ab8b88175a38e05a76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    storageBucket: 'brix-ide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzcZxbyfp7Ro-w6vmfGosoGmMHoBuhuI',
    appId: '1:572765239328:ios:8216e07705f2c101a76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    storageBucket: 'brix-ide.appspot.com',
    androidClientId: '572765239328-idj3pvrj4simsc9irntucji09lgksgg6.apps.googleusercontent.com',
    iosClientId: '572765239328-4u3nbmd7v5e61d4vp1gj5gbdq5d8qff2.apps.googleusercontent.com',
    iosBundleId: 'kr.debrix.foreatide',
  );
}
