// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaPiZBzNv-4_ugmYWMHk_G_5C4TAFHYA',
    appId: '1:572765239328:web:c392b5bdad48a406a76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    authDomain: 'brix-ide.firebaseapp.com',
    storageBucket: 'brix-ide.appspot.com',
    measurementId: 'G-2TZ7KXWQ8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWc2VfQfuRMWAHD7dtaXblAUJtUgyMQJ8',
    appId: '1:572765239328:android:e8ed5c46cef5deaea76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    storageBucket: 'brix-ide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzcZxbyfp7Ro-w6vmfGosoGmMHoBuhuI',
    appId: '1:572765239328:ios:698616949f734c14a76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    storageBucket: 'brix-ide.appspot.com',
    androidClientId: '572765239328-nqti2ut20jhosnjt5ss7moannl6bef50.apps.googleusercontent.com',
    iosClientId: '572765239328-5fml58q8ureid9v8nch20satqo504vka.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfzcZxbyfp7Ro-w6vmfGosoGmMHoBuhuI',
    appId: '1:572765239328:ios:0f65ba607741a62ba76445',
    messagingSenderId: '572765239328',
    projectId: 'brix-ide',
    storageBucket: 'brix-ide.appspot.com',
    androidClientId: '572765239328-nqti2ut20jhosnjt5ss7moannl6bef50.apps.googleusercontent.com',
    iosClientId: '572765239328-ecc2bibn2r8mm03r30rju1tun8mhhamn.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp.temp.RunnerTests',
  );
}
